version: "3.8"
services:
  vuln-flask-server:
    container_name: sqli-lab-error-based
    # M1/M2 users - change the image name to: uwacyber/cits3006:sqli-error-arm64
    image: uwacyber/cits3006:sqli-error
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "1337:1337"

  mysql:
    container_name: mysql
    # M1/M2 users - change the image name to: arm64v8/mysql:8.0.30
    image: mysql:8.0.30
    #M1/M2 users - change the platform to: linux/arm64
    platform: linux/amd64
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: "dbuser"
      MYSQL_PASSWORD: "wowthisissecure"
      MYSQL_DATABASE: "vulndb"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
      start_period: 10s
